### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by RingoTC** [leinue/TidyCSS#2]
1.建议将代码中的“微软雅黑”替换成“Microsoft Yahei”
2.建议使用sass or less ，可以使代码精简
3.动效变幻时间较长，建议缩短时间

**Comment by leinue** [comment]
好的谢谢建议

**Comment by RingoTC** [comment]
这回复也太快了...

**Comment by zisheng-ai** [comment]
为什么停止更新了

**Comment by liunianbanbo** [comment]
已经是三年前的了。现在看看一些视觉设计都是过时了的
